server:
  port: 8080

spring:
  profiles:
    group:
      "common": "jwt, oauth"
    active: common

---
spring:
  config:
    activate:
      on-profile: "common"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauthtest4
    username: root
    password: 3249

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create